name: Basic Github Actions YAML

on: 
    push: 

jobs: 
    testing: 
        name: Testing files
        runs-on: ubuntu-latest
        steps:
            - name: listing files
              run: ls
            - name:  Read the file 
              run: cat  index.html 